name: Deploy to S3

on:
  push:
    branches:
      - main  # Ubah sesuai dengan branch yang Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1  # Singapore region

      - name: Sync static website to S3
        run: |
          aws s3 sync static-website/ s3://new-timmy-11.serverless.my.id --delete
